AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Stack for a AWS Lambdas using Java and NodeJS.

Resources:
  JavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.github.yeghishe.scalaawslambdaseed.MyHandler
      Runtime: java8
      Timeout: 10
      CodeUri: ./target/scala-2.12/scala-aws-lambda-seed.jar
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetJavaResource:
          Type: Api
          Properties:
            Path: /java
            Method: get